modLoader="javafml"
loaderVersion="[39,)"
license="MIT"

# PRIMA MOD - MCCourse
[[mods]]
modId="mccourse"
version="${file.jarVersion}"
displayName="MC Course Mod"
description="Main course mod"
authors="Valerio"

[[dependencies.mccourse]]
modId="forge"
mandatory=true
versionRange="[39.1.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.mccourse]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"

# SECONDA MOD - YoYo
[[mods]]
modId="yoyo"
version="${file.jarVersion}"
displayName="YoYo Mod"
description="A mod that adds a cool yoyo weapon"
authors="Valentina"

[[dependencies.yoyo]]
modId="forge"
mandatory=true
versionRange="[39.1.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.yoyo]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"